name: Tree-sitter update action
description: Update tree-sitter parser dependencies

inputs:
  parent-name:
    description: The parent language name (for scanner updates)
  language-name:
    description: The current language name (for scanner updates)
  pr-branch:
    description: The name of the PR branch
    default: update-parser-pr
  script-body:
    description: The JS function body that returns package links
    default: |-
      return this.map(([key, value]) => {
        const name = key.substring(13), version = value.version;
        return `- [${name}@${version}](https://www.npmjs.com/package/${name}/v/${version})`;
      }).join('\n');

runs:
  using: composite
  steps:
    - name: Update dependencies
      uses: actions/github-script@v7
      id: update
      with:
        result-encoding: string
        script: |-
          const { readFileSync, writeFileSync } = require('node:fs');
          function getBody() {
            const { packages } = JSON.parse(readFileSync('package-lock.json', 'utf8'));
            const entries = Object.entries(packages).slice(1);
            return (function() { ${{inputs.script-body}} }).call(entries);
          }

          core.summary.addRaw('## Old versions', true);
          core.summary.addRaw(getBody(), true).addEOL();
          await core.summary.write();
          await exec.exec('npm', ['update'])

          const body = getBody();
          core.summary.addRaw('## New versions', true);
          core.summary.addRaw(body, true).addEOL();
          await core.summary.write();
          return body;
    - name: Regenerate the parser
      shell: sh
      run: node_modules/.bin/tree-sitter generate --no-bindings
    - name: Update the scanner
      if: inputs.parent-name != ''
      shell: sh
      run: |-
        sed 's/tree_sitter_${{inputs.parent-name}}_/tree_sitter_${{inputs.language-name}}_/' \
          'node_modules/tree-sitter-${{inputs.parent-name}}/src/scanner.c' > src/scanner.c
        git diff -- src/scanner.c
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "build: update & regenerate parser"
        commit_author: >-
          github-actions[bot]
          <41898282+github-actions[bot]@users.noreply.github.com>
        branch: ${{inputs.pr-branch}}
        create_branch: true
        skip_checkout: true
        skip_fetch: true
    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        title: "build: update & regenerate parser"
        author: >-
          github-actions[bot]
          <41898282+github-actions[bot]@users.noreply.github.com>
        body: ${{steps.update.outputs.result}}
        base: ${{github.event.repository.default_branch}}
        branch: ${{inputs.pr-branch}}
        delete-branch: true
