name: Tree-sitter setup action
description: Set up parser repo CI

inputs:
  submodules:
    description: Initialize submodules
    default: 'false'
  node-version:
    description: The NodeJS version
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: ${{inputs.submodules}}
    - name: Set up NodeJS
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{inputs.node-version}}
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.8
      if: runner.os == 'macOS'
    - name: Install dependencies
      shell: sh
      run: npm ci
    - name: Add node modules to PATH
      shell: sh
      run: printf '%s/node_modules/.bin\n' "$PWD" >> "$GITHUB_PATH"
    - name: Configure tree-sitter
      shell: bash
      run: |-
        config="$(tree-sitter init-config | cut -c32- | tr '\\' '/')"
        printf '{"parser-directories":["%q"]}' "$(dirname "$PWD")" > "$config"
